name: Synopsys Intelligent Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  synopsys-io:
    name: Synopsys Intelligent Security Scan (IO)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assert required secrets present
        if: ${{ secrets.IO_SERVER_URL == '' || secrets.IO_SERVER_TOKEN == '' }}
        run: |
          echo "Missing IO_SERVER_URL and/or IO_SERVER_TOKEN"
          exit 1

      - name: Synopsys Intelligent Security Scan
        uses: blackduck-inc/intelligent-security-scan@2023.3.3
        with:
          ioServerUrl: ${{ secrets.IO_SERVER_URL }}
          ioServerToken: ${{ secrets.IO_SERVER_TOKEN }}
          stage: IO
