name: Synopsys Intelligent Security Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  security-scan:
    name: Synopsys Intelligent Security Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Synopsys Intelligent Security Scan
        uses: blackduck-inc/intelligent-security-scan@2023.3.3
        with:
          ioServerUrl: ${{ secrets.IO_SERVER_URL }}
          ioServerToken: ${{ secrets.IO_SERVER_TOKEN }}
          stage: "IO"

          # Optional configuration
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
          coverity_url: ${{ secrets.COVERITY_URL }}
          coverity_token: ${{ secrets.COVERITY_TOKEN }}

        env:
          # Optional proxy support
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
